#!/bin/bash
# My first script

APIM_HOME=.
GIT_HOME=~/wso2apim/gitworkspace
PATCHDIR=$APIM_HOME/repository/components/patches/patch0050
GROUP=org.wso2.carbon.apimgt
COMPONENT=hostobjects

VERSION=1.2.5-SNAPSHOT

mkdir -p $PATCHDIR

echo "Copying target hostobj jar to distribution"

cp $GIT_HOME/carbon-apimgt/components/apimgt/$GROUP.$COMPONENT/target/$GROUP.$COMPONENT'-'$VERSION.jar $PATCHDIR/$GROUP.$COMPONENT'_'$VERSION.jar

echo "Finish"

echo "Listing patch dir"

listpatchdir
