#!/bin/bash

pathResources=~/wso2apim/scripts/resources
patches=$pathResources/temp/patches
target=$patches/$1
APIM_patches=$2/repository/components/patches
APIM_target=$2/repository/components/patches/$1

if [[ $1 = "" ]] 
then
    echoh2 "Please input patch dir."
    echoh3 "Ex:"
    echoh3 "mcinotests-patch patch0050"
else
    # echoh2 "Creating temp patch dir at $target"
    # mkdir -p $target
    echoh1 "Building without tests"
    mvn clean install -Dmaven.test.skip=true --offline
    echoh1 "Generating effective pom"
    mvn help:effective-pom -Doutput=target/effective-pom.xml --offline
    artifactId=$(xpath -q -e '/project/artifactId' target/effective-pom.xml | grep -oP '(?<=artifactId>)[^<]+')
    version=$(xpath -q -e '/project/version' target/effective-pom.xml | grep -oP '(?<=version>)[^<]+')
    echoh3 "Artifact ID:"$artifactId
    echoh3 "Version:"$version
    # echoh2 "Copying $artifactId-$version.jar into $target"
    # cp target/$artifactId-$version.jar $target/$artifactId'_'$version.jar
    # echoh2 "Listing temp dir $target"
    # ls $target --color
    
    if [[ $2 != "" ]]
    then
        echoh2 "APIM target is given. Copying $artifactId-$version.jar into $APIM_target"
        mkdir -p $APIM_target
        cp target/$artifactId-$version.jar $APIM_target/$artifactId'_'$version.jar
        echoh2 "Listing APIM all patch numbers $APIM_patches"
        ls $APIM_patches --color
        echoh2 "Listing APIM patch dir $APIM_target"
        ls $APIM_target --color
    fi
    echoh1 "FINISHED"
fi
